# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Dan Price
email: mail@danprice.dev
description: .Net developer, IT guy, musician, retro gamer, digital artist.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://danprice.dev" # the base hostname & protocol for your site, e.g. http://example.com
paginate: 10

footer-links:
  github: flexplate
  instagram: flexplate
  linkedin:
  rss: rss # just type anything here for a working RSS icon
  twitter: therezin
  youtube: # channel/<your_long_string> or user/<user-name>
  kofi: flexplate
  mastodon: mas.to/@flexplate


# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google-analytics: G-1EGFXY0RY0

plugins:
  - jekyll-sitemap # Generate sitemap
  - jekyll-feed # Generate RSS feed
  - jekyll-paginate

kramdown:
  input: GFM # Github-flavoured Markdown
  parse_block_html: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: compressed
  sass_dir: styles

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - README.md
  - CNAME
